### ISSUE TITLE
Stale maven-metadata.xml

### ISSUE THREAD

**Issue by ben-manes** [ops4j/org.ops4j.pax.exam#1043]
On Maven Central, the published [maven-metadata.xml](https://repo1.maven.org/maven2/org/ops4j/pax/exam/pax-exam-container-native/maven-metadata.xml) lists up to version `4.13.1` and declares it as the latest. However, the repository contains `4.13.4`, which the [search ui](https://search.maven.org/artifact/org.ops4j.pax.exam/pax-exam-container-native) lists as the latest. When using tools that scan for dependency upgrades, this causes incorrect suggestions due to the outdated metadata. Somehow your release process is no longer publishing updates.

```
The following dependencies exceed the version found at the milestone revision level:
 - org.ops4j.pax.exam:pax-exam-container-native [4.13.4 <- 4.13.1]
     http://team.ops4j.org/wiki/display/paxexam/
 - org.ops4j.pax.exam:pax-exam-junit4 [4.13.4 <- 4.13.1]
     http://team.ops4j.org/wiki/display/paxexam/
 - org.ops4j.pax.exam:pax-exam-link-mvn [4.13.4 <- 4.13.1]
     http://team.ops4j.org/wiki/display/paxexam/
 - org.ops4j.pax.url:pax-url-aether [2.6.7 <- 2.6.1]
     ${wiki.url}
```

**Comment by oliverlietz** [comment]
Could be related to [Using MINSTALL/DEPLOY 3.0.0-M1+ does not write plugin information into maven-metadata.xml](https://issues.apache.org/jira/browse/MNG-7055).

**Comment by cstamas** [comment]
This is Maven Central/Sonatype related, strangely versions missing are missing published date metadata as well:
![image](https://github.com/ops4j/org.ops4j.pax.exam2/assets/45165/54ae31af-3311-4eec-9d59-f1788ebecf26)

Created https://issues.sonatype.org/browse/OSSRH-94539

**Comment by ben-manes** [comment]
Confirmed! Thanks for the fix, it removes an ugly workaround.

**Comment by ben-manes** [comment]
I ran a dependency updates and observe this problem again. It seems to have coincided with your release.

```console
The following dependencies exceed the version found at the milestone revision level:
 - org.ops4j.pax.exam:pax-exam-container-native [4.13.5 <- 4.13.1]
     http://team.ops4j.org/wiki/display/paxexam/
 - org.ops4j.pax.exam:pax-exam-junit4 [4.13.5 <- 4.13.1]
     http://team.ops4j.org/wiki/display/paxexam/
 - org.ops4j.pax.exam:pax-exam-link-mvn [4.13.5 <- 4.13.1]
     http://team.ops4j.org/wiki/display/paxexam/
```

The [maven-metadata.xml](https://repo1.maven.org/maven2/org/ops4j/pax/exam/pax-exam-container-native/maven-metadata.xml) says the latest is `4.13.1` and has the timestamp `2018-12-09`. The recent `4.14.0.0` has no directory timestamp like the above. It seems to be a regression on Central.

Forwarded to central-support@sonatype.com

**Comment by oliverlietz** [comment]
@ben-manes, as there is no public issue tracker anymore please add any response from Sonatype here.

**Comment by ben-manes** [comment]
From: Support <central-support@sonatype.com>
Date: Mon, Dec 2, 2024 at 8:27 AM
Subject: [Central Support by Sonatype] Re: Stale maven-metadata

Hello Ben,
 
Thanks for bringing this to our attention, the missing versions have been fixed in maven metadata.
 
 
Regards,
The Central Team

**Comment by oliverlietz** [comment]
It's still broken (https://repo1.maven.org/maven2/org/ops4j/pax/exam/):
```
<a href="1.0.0/" title="1.0.0/">1.0.0/</a>                                            2009-06-22 00:28         -      
<a href="1.1.0/" title="1.1.0/">1.1.0/</a>                                            2009-08-26 09:07         -      
<a href="1.2.0/" title="1.2.0/">1.2.0/</a>                                            2009-10-29 15:11         -      
<a href="1.2.1/" title="1.2.1/">1.2.1/</a>                                            2010-08-13 21:46         -      
<a href="1.2.2/" title="1.2.2/">1.2.2/</a>                                            2010-09-13 07:47         -      
<a href="1.2.3/" title="1.2.3/">1.2.3/</a>                                            2010-12-31 13:04         -      
<a href="1.2.4/" title="1.2.4/">1.2.4/</a>                                            2011-03-01 10:51         -      
<a href="2.0.0/" title="2.0.0/">2.0.0/</a>                                            2011-05-22 20:25         -      
<a href="2.0.0-M1/" title="2.0.0-M1/">2.0.0-M1/</a>                                         2010-11-15 15:25         -      
<a href="2.0.0-RC1/" title="2.0.0-RC1/">2.0.0-RC1/</a>                                        2011-04-05 16:26         -      
<a href="2.0.0-RC2/" title="2.0.0-RC2/">2.0.0-RC2/</a>                                        2011-04-06 14:11         -      
<a href="2.0.0-RC3/" title="2.0.0-RC3/">2.0.0-RC3/</a>                                        2011-04-08 14:07         -      
<a href="2.0.0-RC4/" title="2.0.0-RC4/">2.0.0-RC4/</a>                                        2011-04-15 12:42         -      
<a href="2.0.0-RC5/" title="2.0.0-RC5/">2.0.0-RC5/</a>                                        2011-05-09 12:10         -      
<a href="2.1.0/" title="2.1.0/">2.1.0/</a>                                            2011-05-30 12:22         -      
<a href="2.2.0/" title="2.2.0/">2.2.0/</a>                                            2011-07-22 14:30         -      
<a href="2.3.0/" title="2.3.0/">2.3.0/</a>                                            2011-12-17 11:32         -      
<a href="2.3.0.M1/" title="2.3.0.M1/">2.3.0.M1/</a>                                         2011-09-13 19:16         -      
<a href="2.3.1/" title="2.3.1/">2.3.1/</a>                                            2012-02-27 12:03         -      
<a href="2.4.0/" title="2.4.0/">2.4.0/</a>                                            2012-05-11 13:26         -      
<a href="2.4.0.RC1/" title="2.4.0.RC1/">2.4.0.RC1/</a>                                        2012-02-04 21:22         -      
<a href="2.5.0/" title="2.5.0/">2.5.0/</a>                                            2012-06-26 17:36         -      
<a href="2.6.0/" title="2.6.0/">2.6.0/</a>                                            2012-09-29 16:18         -      
<a href="3.0.0/" title="3.0.0/">3.0.0/</a>                                            2013-01-15 20:48         -      
<a href="3.0.0.M1/" title="3.0.0.M1/">3.0.0.M1/</a>                                         2012-05-24 11:31         -      
<a href="3.0.0.M2/" title="3.0.0.M2/">3.0.0.M2/</a>                                         2012-06-03 16:51         -      
<a href="3.0.0.M3/" title="3.0.0.M3/">3.0.0.M3/</a>                                         2012-07-22 13:10         -      
<a href="3.0.0.M4/" title="3.0.0.M4/">3.0.0.M4/</a>                                         2012-10-03 16:05         -      
<a href="3.0.0.RC1/" title="3.0.0.RC1/">3.0.0.RC1/</a>                                        2012-12-14 18:22         -      
<a href="3.0.1/" title="3.0.1/">3.0.1/</a>                                            2013-03-07 20:14         -      
<a href="3.0.2/" title="3.0.2/">3.0.2/</a>                                            2013-04-02 19:07         -      
<a href="3.0.3/" title="3.0.3/">3.0.3/</a>                                            2013-04-03 17:15         -      
<a href="3.1.0/" title="3.1.0/">3.1.0/</a>                                            2013-06-20 10:08         -      
<a href="3.2.0/" title="3.2.0/">3.2.0/</a>                                            2013-07-27 15:25         -      
<a href="3.3.0/" title="3.3.0/">3.3.0/</a>                                            2013-09-21 16:25         -      
<a href="3.4.0/" title="3.4.0/">3.4.0/</a>                                            2013-12-02 14:09         -      
<a href="3.5.0/" title="3.5.0/">3.5.0/</a>                                            2014-04-27 12:45         -      
<a href="3.6.0/" title="3.6.0/">3.6.0/</a>                                            2015-01-22 21:17         -      
<a href="4.0.0/" title="4.0.0/">4.0.0/</a>                                            2014-06-13 21:34         -      
<a href="4.1.0/" title="4.1.0/">4.1.0/</a>                                            2014-07-28 19:27         -      
<a href="4.10.0/" title="4.10.0/">4.10.0/</a>                                           2017-01-30 21:29         -      
<a href="4.11.0/" title="4.11.0/">4.11.0/</a>                                           2017-05-16 14:12         -      
<a href="4.12.0/" title="4.12.0/">4.12.0/</a>                                           2018-07-05 17:21         -      
<a href="4.13.0/" title="4.13.0/">4.13.0/</a>                                           2018-11-29 09:36         -      
<a href="4.13.1/" title="4.13.1/">4.13.1/</a>                                           2018-12-09 07:14         -      
<a href="4.13.2/" title="4.13.2/">4.13.2/</a>                                           2020-02-21 06:59         -      
<a href="4.13.3/" title="4.13.3/">4.13.3/</a>                                           2020-03-22 15:39         -      
<a href="4.13.4/" title="4.13.4/">4.13.4/</a>                                           2020-09-23 18:26         -      
<a href="4.13.5/" title="4.13.5/">4.13.5/</a>                                           2021-11-21 20:52         -      
<a href="4.14.0/" title="4.14.0/">4.14.0/</a>                                                          -         -      
<a href="4.2.0/" title="4.2.0/">4.2.0/</a>                                            2014-09-01 21:28         -      
<a href="4.3.0/" title="4.3.0/">4.3.0/</a>                                            2014-10-14 20:24         -      
<a href="4.4.0/" title="4.4.0/">4.4.0/</a>                                            2014-12-06 09:55         -      
<a href="4.5.0/" title="4.5.0/">4.5.0/</a>                                            2015-04-17 19:55         -      
<a href="4.6.0/" title="4.6.0/">4.6.0/</a>                                            2015-08-15 15:26         -      
<a href="4.7.0/" title="4.7.0/">4.7.0/</a>                                            2015-12-02 18:20         -      
<a href="4.8.0/" title="4.8.0/">4.8.0/</a>                                            2015-12-18 19:53         -      
<a href="4.9.0/" title="4.9.0/">4.9.0/</a>                                            2016-04-22 09:01         -      
<a href="4.9.1/" title="4.9.1/">4.9.1/</a>                                            2016-04-26 14:50         -      
<a href="4.9.2/" title="4.9.2/">4.9.2/</a>                                            2016-10-19 10:24         -      
```

```
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <versioning>
    <latest>4.13.1</latest>
    <release>4.13.1</release>
    <versions>
      <version>1.0.0</version>
      <version>1.1.0</version>
      <version>1.2.0</version>
      <version>1.2.1</version>
      <version>1.2.2</version>
      <version>1.2.3</version>
      <version>1.2.4</version>
      <version>2.0.0-M1</version>
      <version>2.0.0-RC1</version>
      <version>2.0.0-RC2</version>
      <version>2.0.0-RC3</version>
      <version>2.0.0-RC4</version>
      <version>2.0.0-RC5</version>
      <version>2.0.0</version>
      <version>2.1.0</version>
      <version>2.2.0</version>
      <version>2.3.0.M1</version>
      <version>2.3.0</version>
      <version>2.3.1</version>
      <version>2.4.0.RC1</version>
      <version>2.4.0</version>
      <version>2.5.0</version>
      <version>2.6.0</version>
      <version>3.0.0.M1</version>
      <version>3.0.0.M2</version>
      <version>3.0.0.M3</version>
      <version>3.0.0.M4</version>
      <version>3.0.0.RC1</version>
      <version>3.0.0</version>
      <version>3.0.1</version>
      <version>3.0.2</version>
      <version>3.0.3</version>
      <version>3.1.0</version>
      <version>3.2.0</version>
      <version>3.3.0</version>
      <version>3.4.0</version>
      <version>3.5.0</version>
      <version>3.6.0</version>
      <version>4.0.0</version>
      <version>4.1.0</version>
      <version>4.2.0</version>
      <version>4.3.0</version>
      <version>4.4.0</version>
      <version>4.5.0</version>
      <version>4.6.0</version>
      <version>4.7.0</version>
      <version>4.8.0</version>
      <version>4.9.0</version>
      <version>4.9.1</version>
      <version>4.9.2</version>
      <version>4.10.0</version>
      <version>4.11.0</version>
      <version>4.12.0</version>
      <version>4.13.0</version>
      <version>4.13.1</version>
    </versions>
    <lastUpdated>20181209073112</lastUpdated>
  </versioning>
  <plugins>
    <plugin>
      <name>OPS4J Pax Exam Maven Plugin</name>
      <prefix>exam</prefix>
      <artifactId>exam-maven-plugin</artifactId>
    </plugin>
    <plugin>
      <name>OPS4J Pax Exam - Maven Plugin</name>
      <prefix>paxexam</prefix>
      <artifactId>maven-paxexam-plugin</artifactId>
    </plugin>
  </plugins>
</metadata>
```

**Comment by ben-manes** [comment]
Thank you. Unfortunately, the maintainers noticed it is still broken for
their other artifacts (cc'd).

**Comment by ben-manes** [comment]
@oliverlietz they asked to review the modules with you so I cc'd using the info email address from your git commit.

**Comment by oliverlietz** [comment]
Root cause (old sync with outdated OPS4J staging repo) is fixed.
See [discussion in the Maven channel for details](https://the-asf.slack.com/archives/C7Q9JB404/p1733211836021439).

**Comment by ben-manes** [comment]
> See [discussion in the Maven channel for details](https://the-asf.slack.com/archives/C7Q9JB404/p1733211836021439).

fwiw, I think that is private to Apache members. Thanks for helping get this resolved.

**Comment by oliverlietz** [comment]
@ben-manes, Access to [ASF Slack](https://infra.apache.org/slack.html) is managed via invitations to prevent spamming.
